name: Auto Format
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npx prettier --write .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code"
